### ISSUE TITLE
[BUG] Relationships

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/deepcove-website#15]
Need to correact relationships between pages, page revisions, text fields and links. @jacksos101

Currently Page.LatestRevision or Page.Revisions returns null

**Comment by jacksos101** [comment]
If you add `ToList()` between your `Include` and `Select` calls, then EF Core should correctly populate the navigation properties.

```
var data = _Db.Pages.Include(i => i.PageRevisions)
                .ToList()
                .Select(s => new { ...
```

**Comment by samuelgrant** [comment]
Okay, this looks to be resolved. I can re-open the issue if I continue to have issues. Thank you.
