### ISSUE TITLE
Develop Media Management System

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/deepcove-website#78]
> Develop a media upload system (Images, files etc. This is for both the website and mobile CMS) 

- [x] Create the models
- [x] Create the migration
- [x] Develop the admin functions
   - [x] Gallery
   - [x] Upload
   - [x] Meta Data (View/Adjust)
   - [x] Delete
- [x] Media Fields - Build a component that:
   - [x] Knows it's size
   - [x] Requests an image that is correct
   - [x] Displays the image, or alt text if needed

**Comment by jacksos101** [comment]
As per discussion:

#### How do we avoid serving huge images to browsers that only require a small image?
> Upon uploading an image, the server will save multiple smaller copies of that image; each copy will be suitable for displaying at a certain size. For example, an image that is 4MB will have a small thumbnail version (~50kB), a small version (~200kB), a medium (~500kB) and a large (~1MB) in addition to the original. Smaller uploaded images will not require as many copies to be made. When a UI component requires an image, it will calculate its own size, then send a request for the image to the server, along with its size requirements. The server will determine the appropriate sized image to return.

#### Do we store all of these copies upon upload, or do we lazily create them as they are requested?
> The benefits of lazily creating and storing smaller copies would be reduced storage requirements on the server. However, because the website will not be handling huge volumes of images, we feel that storing copies immediately will not use an excessive amount of storage space. This is especially true given that the small copies of images will take very little space. 
Storing them upon upload also reduces the time that clients will have to wait for images, should they request sizes that have not previously been created and stored.

#### How does the user have to format large image, prior to uploading?
> The website should not be serving large images to visitors, as this will have a detrimental impact on loading times and data consumption. Therefore, images larger than 1MB will need to be scaled down prior to being displayed on the site. We have two options - either make the user scale the image down in their own image editing software, or scale the image down for them after they have uploaded it. We will attempt to scale the image for them, as this reduces their workload and their required skillset.
