### ISSUE TITLE
Properties section of media files is incorrect for non-images

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/deepcove-website#92]
The Audio Properties section should show the duration, but is currently showing title, alt text and dimensions. 

The properties section of general documents does not have to be displayed, I believe, as there aren't any specific details to show there.

**Comment by samuelgrant** [comment]
@jacksos101 Can you make sure the duration is in seconds.  i'm looking at kea call and it shows up as a 0

**Comment by samuelgrant** [comment]
UI elements for this have been resolved, but I'm waiting on the correct number of seconds to be passed back through
